### ISSUE TITLE
ObjectNet3D dataset

### ISSUE THREAD

**Issue by mmahdavian** [yshah43/DPOD#6]
Hi 

Is there anyway to train your models on ObjectNet3D dataset? As it has 100 categories and it can be more practical. 

Thank You

**Comment by yshah43** [comment]
You can train the model on any dataset as long as the dataset has 3D point clouds for each object and the ground truth rotation and translation for the object in a given RGB image.
Note: There might be some minor changes to be made to the code given that there would be  100 categories now.
