### ISSUE TITLE
Hi, sir!  Did you reproduce the results of the pose estimation experiments on the LineMOD dataset reported in the article？

### ISSUE THREAD

**Issue by zhoushiqi47** [yshah43/DPOD#7]

**Comment by yshah43** [comment]
No I didn't get the accuracy in the paper. I believe I need to do add data augmentation (check the #1 on to do list).
This is a data hungry model and using just 15% of Linemod isn't enough data.

**Comment by hiyyg** [comment]
@yshah43 How much can you achieve right now?

**Comment by yshah43** [comment]
68.7%
